### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by KTSCode** [katietensfeldt/flicks-frontend#13]
### User Story
**As a user, I want to sign up for flicks using my Gmail account so that I don't have to manage another set of login credentials.**

**Comment by katietensfeldt** [comment]
Have redirect go back to '/dashboard' - to display individual user's dashboard.

Do we need further design for this page?

**Comment by KTSCode** [comment]
@Katie10sfeldt nope we already have the buttons working so that should be just fine
